version: '3'
services:
  #######################
  # Setup node server
  #######################

  server:
    container_name: train-ticker-server
    build:
      context: ./server/
      dockerfile: Dockerfile
    image: lkhaliliu/qunar-server
    ports:
      - '8080:8080'
    volumes:
      - ./server:/srv/app
    command: npm run dev

  #######################
  # Setup client container
  #######################
  client:
    container_name: train-ticker-client
    build:
      context: ./client/
      dockerfile: Dockerfile
    image: lkhaliliu/qunar-client
    ports:
      - '3000:3000'
    depends_on:
      - server
    volumes:
      - ./client:/srv/app
    command: npm run start
